#code6.14
#defaults:
  #- params: exp1


#code6.12
params:
  batch_size: 16
  learning_rate: 0.01

#code6.16
defaults:
  - model: duration_dnn

#ログ出力の詳細度を設定しており，100だと非常に詳細にデバッグや処理の進行状況が確認できる．
verbose: 100
#ランダムシードを固定することで，再現性が高くなる．
seed: 773

cudnn:
  #cuDNNに最適なアルゴリズムを探索させる
  benchmark: true
  #性能>再現性
  deterministic: false


#code6.17
#この階層で設定を変更できるようにしている．
#空欄はコマンドラインプログラムを実行するときに，引数から指定されることを想定．
data:
  #training set
  train:
    utt:list: data/train.list
    in_dir:
    out_dir:

  #development set
  dev:
    utt:list: data/dev.list
    in_dir:
    out_dir:

  #data loader
  num_workers: 4
  batch_size: 32

#code6.18
train:
  out_dir: exp
  log_dir: tensorboard/exp

  max_train_steps: -1
  nepochs: 30
  checkpoint_epoch_interval: 10

  optim:
    optimizer:
      name: Adam
      params:
        lr: 0.001
        betas: [0.9, 0.999]
        weight_decay: 0.0
    lr_scheduler:
      name: StepLR
      params:
        step_size: 10
        gamma: 0.5
